name: Release
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
      - uses: actions/checkout@v4
        run: pip install uv
      - name: Build
        run: uv build 
      - name: Run Tests
        run: uv run pytest