name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup uv
        uses: astral-sh/setup-uv@v4
        with: 
            version: "0.4.15"
            enable-cache: true
            cache-dependency-glob: |
              requirements**.txt
              pyproject.toml
  
      - name: Build release distributions
        run: uv build

      - name: Run tests
        run: uv run pytest
        